name: alumea
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  routemaster: ^1.0.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  googleapis_auth: ^2.0.0
  fpdart: ^1.1.1
  rxdart: ^0.28.0
  equatable: ^2.0.7
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  cloud_functions: ^5.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"