// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhI1DX5T9X5JP0iTZvQG-ugBDPmGuOGEM',
    appId: '1:690102196204:web:9add84fc9ea839cf4e12c9',
    messagingSenderId: '690102196204',
    projectId: 'alumea-d1912',
    authDomain: 'alumea-d1912.firebaseapp.com',
    storageBucket: 'alumea-d1912.firebasestorage.app',
    measurementId: 'G-57D3X87G55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5Icmt34oglzjzYQVGVsj96iUGiBPZB4',
    appId: '1:690102196204:android:c67cea4498d787c54e12c9',
    messagingSenderId: '690102196204',
    projectId: 'alumea-d1912',
    storageBucket: 'alumea-d1912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVq56ClOKAtbk6_dnrlA1_Xg-ogWW5r4',
    appId: '1:690102196204:ios:d60623101621d5174e12c9',
    messagingSenderId: '690102196204',
    projectId: 'alumea-d1912',
    storageBucket: 'alumea-d1912.firebasestorage.app',
    androidClientId: '690102196204-6rincnlngjq9ih4nuptlmg2qj4b7jtbe.apps.googleusercontent.com',
    iosClientId: '690102196204-n2nol7ds1vipro8eb6qlnhntjh7u6n2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.alumea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOVq56ClOKAtbk6_dnrlA1_Xg-ogWW5r4',
    appId: '1:690102196204:ios:d60623101621d5174e12c9',
    messagingSenderId: '690102196204',
    projectId: 'alumea-d1912',
    storageBucket: 'alumea-d1912.firebasestorage.app',
    androidClientId: '690102196204-6rincnlngjq9ih4nuptlmg2qj4b7jtbe.apps.googleusercontent.com',
    iosClientId: '690102196204-n2nol7ds1vipro8eb6qlnhntjh7u6n2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.alumea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhI1DX5T9X5JP0iTZvQG-ugBDPmGuOGEM',
    appId: '1:690102196204:web:de1da5bbc781e4184e12c9',
    messagingSenderId: '690102196204',
    projectId: 'alumea-d1912',
    authDomain: 'alumea-d1912.firebaseapp.com',
    storageBucket: 'alumea-d1912.firebasestorage.app',
    measurementId: 'G-9GNKNW43BM',
  );
}
